[project]
name = "aiokalshi"
version = "0.0.1"
description = "An asyncio-native Kalshi API."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.12.0",
    "structlog>=25.4.0",
    "yarl>=1.22.0",
]
